// ---- BITMAP BRUSH (v1 spike, 2026-07) ----
// A second, PARALLEL brush category alongside the existing all-vector
// brush-texture presets (applyBrushTexture, tools.js — jittered Path dab
// copies, ~170/stroke per CLAUDE.md's own perf numbers). Deliberately NOT a
// replacement: the vector presets stay untouched because some exports
// (Rive in particular) need real vector geometry per dab — see
// docs/raster-brush-texture-proposal.md for the full design discussion.
//
// This module produces a single Raster (real bitmap texture, stamped along
// the Draw tool's captured centerline) instead of hundreds of vector Path
// copies. Deliberately built on Paper's existing Raster item type rather
// than inventing a new one — Raster is ALREADY a first-class citizen
// everywhere a stroke needs to be (serR/desR, buildSceneJson, selectedPaths
// construction, save/load) confirmed by grep before writing this, so this
// file only needs to PRODUCE a Raster correctly; every consumer already
// handles it with zero changes.
//
// v1 scope, explicitly NOT done here: tip shapes are procedural only (no
// ABR import yet — the tip-rendering functions below are the plug point
// for that later). Only wired into draw-bridge.js's plain constant-width
// commit path (NOT vector-brush/fill-brush, matching applyBrushTexture's
// own pre-existing scoping).
//
// Live drag preview (added this pass): does NOT go through the Rust
// engine's JSON scene bridge at all — re-serializing a growing PNG to
// base64 into JSON on every pointermove would get slower as the stroke
// grows (the exact "ça rame en dessinant" problem this app's whole
// engine-bridge architecture exists to avoid). Instead, a plain DOM
// <canvas> is layered directly on top of the Rust canvas
// (position:absolute, pointer-events:none, same insertion pattern
// engine-bridge.js uses for rustCanvas itself) and stamped to INCREMENTALLY
// in screen space — each pointermove only draws the new segment since the
// last one, never redraws the whole stroke, so cost per move stays roughly
// constant regardless of stroke length. Purely a preview approximation
// (screen-space stamping, not world-space) — the actual committed Raster
// on pointerup is baked fresh from the real world-space samples by
// stampBitmapBrush below, unaffected by whatever the live preview drew.
(function () {
  var TIP_SIZE = 64; // procedural tip canvas resolution, px — independent of brush Size (that's a WORLD-space display size, this is just texture detail)

  // ---- procedural tips (v1 — plug point for ABR-imported tip masks later:
  // an ABR tip is already a grayscale bitmap mask, so a future importer just
  // needs to draw ITS pixels into a same-shaped canvas instead of these) ----
  function drawSoftTip(ctx, seed) {
    var g = ctx.createRadialGradient(TIP_SIZE / 2, TIP_SIZE / 2, 0, TIP_SIZE / 2, TIP_SIZE / 2, TIP_SIZE / 2);
    g.addColorStop(0, 'rgba(255,255,255,1)');
    g.addColorStop(0.7, 'rgba(255,255,255,.55)');
    g.addColorStop(1, 'rgba(255,255,255,0)');
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, TIP_SIZE, TIP_SIZE);
  }
  function drawGrainTip(ctx, seed) {
    var rng = seededRng(seed);
    var cx = TIP_SIZE / 2, cy = TIP_SIZE / 2, r = TIP_SIZE / 2;
    // Soft falloff base so the grain has an overall round silhouette, not a square.
    drawSoftTip(ctx, seed);
    ctx.globalCompositeOperation = 'source-atop';
    var n = 220;
    for (var i = 0; i < n; i++) {
      var a = rng() * Math.PI * 2, d = Math.sqrt(rng()) * r;
      var x = cx + Math.cos(a) * d, y = cy + Math.sin(a) * d;
      var s = 0.6 + rng() * 1.6;
      ctx.fillStyle = 'rgba(0,0,0,' + (0.15 + rng() * 0.35) + ')';
      ctx.beginPath(); ctx.arc(x, y, s, 0, Math.PI * 2); ctx.fill();
    }
    ctx.globalCompositeOperation = 'source-over';
  }
  function drawSplatterTip(ctx, seed) {
    var rng = seededRng(seed);
    var cx = TIP_SIZE / 2, cy = TIP_SIZE / 2, r = TIP_SIZE / 2;
    var blobs = 5 + Math.floor(rng() * 4);
    for (var i = 0; i < blobs; i++) {
      var a = rng() * Math.PI * 2, d = rng() * r * 0.55;
      var x = cx + Math.cos(a) * d, y = cy + Math.sin(a) * d;
      var br = r * (0.35 + rng() * 0.5);
      var g = ctx.createRadialGradient(x, y, 0, x, y, br);
      g.addColorStop(0, 'rgba(255,255,255,.9)');
      g.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = g;
      ctx.beginPath(); ctx.arc(x, y, br, 0, Math.PI * 2); ctx.fill();
    }
  }
  // Expanded procedural set (2026-07, "récupère des abr open source en
  // preset" — no tool available in this environment to fetch/verify-license
  // a real third-party .abr, see the panel-reorg commit message for the
  // full explanation; these are all generated by code, so there's no
  // licensing question at all, same posture as the 3 originals). Grouped
  // to mirror the vector brush picker's own category convention
  // (brush-preset-picker.js's builtinGroups) — see TIP_GROUPS below.
  function drawHardTip(ctx, seed) {
    ctx.fillStyle = '#fff';
    ctx.beginPath(); ctx.arc(TIP_SIZE / 2, TIP_SIZE / 2, TIP_SIZE / 2 - 1, 0, Math.PI * 2); ctx.fill();
  }
  function drawCharcoalRoughTip(ctx, seed) {
    var rng = seededRng(seed);
    var cx = TIP_SIZE / 2, cy = TIP_SIZE / 2, r = TIP_SIZE / 2;
    // Irregular polygon silhouette (not a clean circle) for a broken,
    // torn-edge charcoal-chunk feel, then grain on top.
    ctx.beginPath();
    var pts = 14;
    for (var i = 0; i <= pts; i++) {
      var a = (i / pts) * Math.PI * 2;
      var rr = r * (0.7 + rng() * 0.3);
      var x = cx + Math.cos(a) * rr, y = cy + Math.sin(a) * rr;
      if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
    }
    ctx.closePath();
    ctx.fillStyle = '#fff'; ctx.fill();
    ctx.globalCompositeOperation = 'source-atop';
    var n = 160;
    for (var j = 0; j < n; j++) {
      var a2 = rng() * Math.PI * 2, d2 = Math.sqrt(rng()) * r;
      ctx.fillStyle = 'rgba(0,0,0,' + (0.2 + rng() * 0.4) + ')';
      ctx.beginPath(); ctx.arc(cx + Math.cos(a2) * d2, cy + Math.sin(a2) * d2, 0.5 + rng() * 1.4, 0, Math.PI * 2); ctx.fill();
    }
    ctx.globalCompositeOperation = 'source-over';
  }
  function drawDryBrushTip(ctx, seed) {
    var rng = seededRng(seed);
    var cx = TIP_SIZE / 2, cy = TIP_SIZE / 2, r = TIP_SIZE / 2;
    // Radial streaks fanning from center — bristle-separation look.
    var streaks = 18;
    for (var i = 0; i < streaks; i++) {
      var a = rng() * Math.PI * 2;
      var len = r * (0.5 + rng() * 0.5);
      var w = 0.8 + rng() * 1.8;
      ctx.strokeStyle = 'rgba(255,255,255,' + (0.4 + rng() * 0.5) + ')';
      ctx.lineWidth = w; ctx.lineCap = 'round';
      ctx.beginPath();
      ctx.moveTo(cx, cy);
      ctx.lineTo(cx + Math.cos(a) * len, cy + Math.sin(a) * len);
      ctx.stroke();
    }
  }
  function drawWatercolorEdgeTip(ctx, seed) {
    var rng = seededRng(seed);
    var cx = TIP_SIZE / 2, cy = TIP_SIZE / 2, r = TIP_SIZE / 2;
    // Layered soft blobs at slightly different offsets/radii — a pooled,
    // uneven-density wash edge instead of one clean falloff.
    for (var i = 0; i < 5; i++) {
      var ox = (rng() - 0.5) * r * 0.4, oy = (rng() - 0.5) * r * 0.4;
      var rr = r * (0.6 + rng() * 0.4);
      var g = ctx.createRadialGradient(cx + ox, cy + oy, 0, cx + ox, cy + oy, rr);
      g.addColorStop(0, 'rgba(255,255,255,' + (0.35 + rng() * 0.25) + ')');
      g.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, TIP_SIZE, TIP_SIZE);
    }
  }
  function drawInkSplatterFineTip(ctx, seed) {
    var rng = seededRng(seed);
    var cx = TIP_SIZE / 2, cy = TIP_SIZE / 2, r = TIP_SIZE / 2;
    ctx.fillStyle = '#fff';
    ctx.beginPath(); ctx.arc(cx, cy, r * 0.45, 0, Math.PI * 2); ctx.fill();
    var n = 30;
    for (var i = 0; i < n; i++) {
      var a = rng() * Math.PI * 2, d = r * (0.4 + rng() * 0.55);
      var s = 0.5 + rng() * 2.2;
      ctx.beginPath(); ctx.arc(cx + Math.cos(a) * d, cy + Math.sin(a) * d, s, 0, Math.PI * 2); ctx.fill();
    }
  }
  function drawStippleTip(ctx, seed) {
    var rng = seededRng(seed);
    var cx = TIP_SIZE / 2, cy = TIP_SIZE / 2, r = TIP_SIZE / 2;
    var n = 90;
    for (var i = 0; i < n; i++) {
      var a = rng() * Math.PI * 2, d = Math.sqrt(rng()) * r;
      ctx.fillStyle = 'rgba(255,255,255,' + (0.5 + rng() * 0.5) + ')';
      ctx.beginPath(); ctx.arc(cx + Math.cos(a) * d, cy + Math.sin(a) * d, 1.2 + rng() * 1.5, 0, Math.PI * 2); ctx.fill();
    }
  }
  function drawMarkerFlatTip(ctx, seed) {
    // Flat chisel-tip rectangle (rotated), constant coverage — a marker/
    // highlighter nib rather than a round brush.
    ctx.save();
    ctx.translate(TIP_SIZE / 2, TIP_SIZE / 2);
    ctx.rotate(-0.35);
    ctx.fillStyle = '#fff';
    ctx.fillRect(-TIP_SIZE * 0.46, -TIP_SIZE * 0.2, TIP_SIZE * 0.92, TIP_SIZE * 0.4);
    ctx.restore();
  }
  var TIP_DRAWERS = {
    soft: drawSoftTip, hard: drawHardTip, grain: drawGrainTip,
    'charcoal-rough': drawCharcoalRoughTip, 'dry-brush': drawDryBrushTip, 'watercolor-edge': drawWatercolorEdgeTip,
    splatter: drawSplatterTip, 'ink-splatter-fine': drawInkSplatterFineTip, stipple: drawStippleTip,
    'marker-flat': drawMarkerFlatTip,
  };
  // Grouped for the tip picker popover (bitmap-tip-picker.js), mirroring
  // brush-preset-picker.js's builtinGroups() convention exactly.
  var TIP_GROUPS = [
    { label: 'Basique', keys: ['soft', 'hard', 'grain'] },
    { label: 'Matière naturelle', keys: ['charcoal-rough', 'dry-brush', 'watercolor-edge'] },
    { label: 'Éclaboussure', keys: ['splatter', 'ink-splatter-fine', 'stipple'] },
    { label: 'Marqueur', keys: ['marker-flat'] },
  ];
  // ABR-imported tips (importAbr below) — id -> {name, canvas: TIP_SIZE²
  // grayscale-as-alpha canvas, already normalized at import time}. Kept
  // separate from TIP_DRAWERS (procedural, seed-varying) since an
  // imported tip is a fixed bitmap, not a function to invoke with a seed.
  var customTips = {};

  // Deterministic per-stroke RNG (same reasoning as tools.js's seededRng for
  // dab re-stamping on generated tween frames: a fresh Math.random() per
  // regeneration would make the texture visibly "boil" between saves/undos
  // touching the same stroke; not wired into tween regen yet in v1 since
  // Raster strokes don't currently participate in tween matching at all —
  // see the file-header TODO — but keeping this deterministic now avoids
  // having to revisit the stamping math later just to add determinism).
  function seededRng(seed) {
    var s = seed >>> 0;
    return function () { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; };
  }

  function buildTipCanvas(tipName, seed) {
    if (customTips[tipName]) return customTips[tipName].canvas;
    var c = document.createElement('canvas'); c.width = TIP_SIZE; c.height = TIP_SIZE;
    var ctx = c.getContext('2d');
    (TIP_DRAWERS[tipName] || drawSoftTip)(ctx, seed);
    return c;
  }

  // ---- v2 (2026-07): anchor-path + raster-companion architecture ----
  // v1 committed the baked Raster ALONE, throwing the vector geometry away
  // — which broke everything the proposal doc promised ("vector stays the
  // source of truth"): no subselect (a raster has no nodes), no fill (the
  // Path that would have carried fillColor never existed), clicks selected
  // the raster's rectangle instead of the stroke. Reported live: "subselect
  // ne marche pas... le fond n'apparaît pas". v2 mirrors applyBrushTexture's
  // (tools.js) proven anchor+companions pattern exactly: the ordinary
  // vector Path IS committed (fill kept visible, stroke camouflaged via
  // preTextureStroke/preTextureOpacity, same rules), and the baked texture
  // is ONE companion Raster tagged isBrushTextureCopy + brushGroupId —
  // which existing machinery then handles for free: selection exclusion
  // (isSelectablePathChild), group move, relinkBrushCompanions after every
  // loadFrame, and regenerateBrushTexture's re-stamp on subselect drag-end.
  //
  // Also fixed here vs v1's stamping:
  // - "1s d'attente après le relâchement": the raster is now created from
  //   the baked <canvas> ELEMENT directly (synchronous, .loaded is true
  //   immediately) instead of a PNG data URI that had to be encoded then
  //   async-decoded back. The dataURL is still computed for .data.src
  //   (persistence needs a string), but display no longer waits on it.
  // - "la taille est différente du trait": v1 fed each sample's stored
  //   width (an ABSOLUTE px value, e.g. brushSize=3) into the stamp size
  //   as if it were a pressure MULTIPLIER — baking 3x-too-big stamps
  //   (baseSize 40 × width 3 = 120px) while the live preview correctly
  //   used ~1. The walk below stamps at the panel's Size directly.
  // - Corner-cutting: walking raw committed segments linearly ignored the
  //   curve handles Paper's simplify() produced; path.getPointAt() walks
  //   the TRUE curve.
  // `rawSamples` (optional, draw-bridge.js's own [x,y,widthPx] array for
  // THIS gesture — tools.js's fallback has none, see its own call site
  // comment) — real tablet-pressure support ("pression de brush avec
  // tablet"): each sample's captured width (already pressure-shaped by
  // widthFor(), draw-bridge.js — Pressure min/max/curve panel settings
  // all already apply) is normalized against state.brushSize into a
  // ratio and stored on the anchor as data.bitmapPressure — a parallel
  // point cloud the stamp walk below looks up by NEAREST position (not
  // by segment index: simplify() doesn't preserve a 1:1 mapping to raw
  // samples, but the anchor's simplified geometry stays close to the
  // original points, so nearest-neighbor gives a good enough per-position
  // estimate without a precise arc-length remap). A later subselect
  // reshape leaves this profile stale relative to the NEW geometry —
  // accepted approximation, same class of shortcut as this file's other
  // v1/v2 choices, not worth a full re-capture mechanism for.
  function applyBitmapBrushTexture(basePath, spec, rawSamples) {
    if (!basePath || !basePath.segments || basePath.segments.length < 2) return basePath;
    spec = spec || {
      tip: state.bitmapTip || 'soft',
      size: state.bitmapSize || 40,
      spacing: state.bitmapSpacing != null ? state.bitmapSpacing : 15,
      scatter: state.bitmapScatter != null ? state.bitmapScatter : 20,
      opacity: (state.bitmapOpacity != null ? state.bitmapOpacity : 100) / 100,
      // The anchor's own strokeColor (already a Paper Color here) is the
      // authoritative ink — state.strokeColor as fallback for a re-apply
      // where camouflage already nulled it and no preTextureStroke exists.
      color: basePath.strokeColor ? colorHex8(basePath.strokeColor) : ((basePath.data && basePath.data.preTextureStroke) || state.strokeColor || '#000000'),
      pressure: !!state.bitmapPressure,
      seed: Math.floor(Math.random() * 0xffffffff),
    };
    // Storing the profile only requires fresh raw samples (a real draw
    // gesture); bakeToCanvas below gates actually USING it on spec.pressure,
    // so a stale leftover profile from a previous apply is inert, not
    // wrong, whenever pressure is off — no need to explicitly clear it on
    // every call (regenerate()/liveRestamp() call this with no rawSamples
    // at all and must keep relying on the ORIGINAL draw's stored profile).
    if (rawSamples && rawSamples.length && spec.pressure) {
      var refSize = state.brushSize || 1;
      basePath.data.bitmapPressureProfile = rawSamples.map(function (s) { return [s[0], s[1], Math.max(0.2, Math.min(2.5, s[2] / refSize))]; });
    }
    var bake = bakeToCanvas(basePath, spec, null);

    // Raster from the canvas ELEMENT — synchronous, no decode wait. The
    // dataURL is still needed as the persistable .data.src string (serR).
    var canvas = bake.canvas, minX = bake.minX, minY = bake.minY, w = bake.w, h = bake.h;
    var raster = new Raster(canvas);
    raster.data.src = canvas.toDataURL('image/png');
    raster.data.isBrushTextureCopy = true; // rides every existing exclusion/move/relink rule for texture companions
    raster.data.isBitmapBrush = true;
    var gid = basePath.data.brushGroupId || ('bmb' + Date.now().toString(36) + '_' + Math.floor(Math.random() * 1e6));
    raster.data.brushGroupId = gid;
    raster.position = new Point(minX + w / 2, minY + h / 2);
    raster.size = new Size(w, h);
    raster.insertAbove(basePath);

    // Anchor camouflage — applyBrushTexture's exact rules: with a fill the
    // path keeps painting it and only the strokeColor goes (remembered);
    // without one, the whole path goes invisible.
    if (basePath.fillColor) {
      if (basePath.data.preTextureStroke === undefined) basePath.data.preTextureStroke = basePath.strokeColor ? colorHex8(basePath.strokeColor) : null;
      basePath.strokeColor = null;
    } else {
      if (basePath.data.preTextureOpacity === undefined) basePath.data.preTextureOpacity = basePath.opacity !== undefined ? basePath.opacity : 1;
      basePath.opacity = 0;
    }
    basePath.data.brushGroupId = gid;
    basePath.data.brushCompanions = [raster];
    basePath.data.bitmapBrushSpec = spec; // persisted via serP — regenerateBrushTexture re-stamps from this after node edits
    return basePath;
  }

  // The bake itself, shared by the initial apply, the drag-end regenerate,
  // and the per-move live restamp — one implementation so the live preview
  // and the committed texture can never drift apart visually. `reuseCanvas`
  // (live restamp) draws into an existing canvas element instead of
  // allocating one per pointermove.
  function bakeToCanvas(basePath, spec, reuseCanvas) {
    var baseSize = spec.size;
    var spacing = Math.max(1, baseSize * (spec.spacing / 100));
    var scatterPx = baseSize * (spec.scatter / 100);
    var rng = seededRng(spec.seed);

    // World-space bounds from the path's own true bounds, padded for tip
    // radius (max jitter scale 1.25) + scatter.
    var pb = basePath.bounds;
    var pad = baseSize * 1.25 / 2 + scatterPx + 4;
    var minX = pb.x - pad, minY = pb.y - pad;
    var w = Math.max(1, pb.width + pad * 2), h = Math.max(1, pb.height + pad * 2);

    // Oversample vs world units for reasonable quality regardless of zoom —
    // a real "resample at export resolution" step is future work. CLAMPED
    // to a max texture dimension: found live (zoomed out to 3%, stroke
    // spanning ~8000 world px) that an unclamped w*2 bake canvas hit
    // ~16000px wide and the synchronous toDataURL froze the app for 30s+.
    // World size of a stroke is unbounded (it scales with 1/zoom for the
    // same hand gesture), so the RESOLUTION must not follow it linearly.
    var MAX_TEX = 4096;
    var SCALE = Math.min(2, MAX_TEX / w, MAX_TEX / h);
    var canvas = reuseCanvas || document.createElement('canvas');
    canvas.width = Math.max(1, Math.ceil(w * SCALE)); canvas.height = Math.max(1, Math.ceil(h * SCALE)); // setting width/height also clears a reused canvas
    var ctx = canvas.getContext('2d');
    var tip = buildTipCanvas(spec.tip, spec.seed);

    // Mask pass: stamp the white/alpha tip at fixed arc-length steps, then
    // tint once via destination-in.
    //
    // Walked along the STRAIGHT-LINE polyline through basePath's own
    // segment points, NOT basePath.getPointAt() (the fitted Bezier curve)
    // — found live ("double trait quand on tourne la brush dans tous les
    // sens rapidement"): a sharp zigzag reversal makes Paper's curve-fit
    // handles overshoot into a small self-intersecting LOOP at the cusp
    // (confirmed by sampling: walking 20 arc-length units forward along
    // the curve at a reversal point only advanced the actual on-screen
    // position ~3px — the curve nearly retraces itself in real space
    // while arc length keeps climbing), so fixed-arc-length stamping
    // re-stamped almost the same spot several times right at each turn —
    // exactly the doubling. The raw segment polyline can't loop (it's
    // straight lines between the actual drawn points, same shape the
    // live preview already walks without this problem) at the cost of
    // ignoring the anchor's curve handles for stamping purposes — texture
    // placement doesn't need bezier-exact precision, spacing already
    // jitters it.
    var maskCanvas = document.createElement('canvas');
    maskCanvas.width = canvas.width; maskCanvas.height = canvas.height;
    var mctx = maskCanvas.getContext('2d');
    var segs = basePath.segments;
    var acc = 0;
    // Real tablet pressure ("pression de brush avec tablet"): nearest-
    // sample lookup into the profile applyBitmapBrushTexture stored from
    // the actual drawing gesture — see that function's own comment for
    // why nearest-neighbor, not arc-length remap. O(stamps × samples) —
    // fine at drawing-gesture scale (dozens to low hundreds of each), not
    // worth a spatial index for.
    var profile = spec.pressure ? basePath.data.bitmapPressureProfile : null;
    var pressureAt = function (x, y) {
      if (!profile || !profile.length) return 1;
      var best = profile[0], bestD = Infinity;
      for (var pi = 0; pi < profile.length; pi++) {
        var dxp = profile[pi][0] - x, dyp = profile[pi][1] - y, dp = dxp * dxp + dyp * dyp;
        if (dp < bestD) { bestD = dp; best = profile[pi]; }
      }
      return best[2];
    };
    var stampAt = function (x, y) {
      var jx = (rng() - 0.5) * 2 * scatterPx, jy = (rng() - 0.5) * 2 * scatterPx;
      var s = baseSize * (0.75 + rng() * 0.5) * pressureAt(x, y);
      var px = (x + jx - minX) * SCALE, py = (y + jy - minY) * SCALE, ps = s * SCALE;
      mctx.globalAlpha = spec.opacity;
      mctx.drawImage(tip, px - ps / 2, py - ps / 2, ps, ps);
    };
    if (segs.length) stampAt(segs[0].point.x, segs[0].point.y);
    for (var si = 0; si < segs.length - 1; si++) {
      var a2 = segs[si].point, b2 = segs[si + 1].point;
      var dx2 = b2.x - a2.x, dy2 = b2.y - a2.y;
      var segLen2 = Math.sqrt(dx2 * dx2 + dy2 * dy2);
      if (segLen2 < 1e-6) continue;
      while (acc < segLen2) {
        var t2 = acc / segLen2;
        stampAt(a2.x + dx2 * t2, a2.y + dy2 * t2);
        acc += spacing;
      }
      acc -= segLen2;
    }
    if (basePath.closed && segs.length) stampAt(segs[0].point.x, segs[0].point.y);
    ctx.fillStyle = spec.color;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.globalCompositeOperation = 'destination-in';
    ctx.drawImage(maskCanvas, 0, 0);
    ctx.globalCompositeOperation = 'source-over';
    return { canvas: canvas, minX: minX, minY: minY, w: w, h: h };
  }

  // Live re-stamp during a subselect node drag ("la ligne texturée ne suit
  // pas en temps réel, que au relâchement") — re-bakes the companion's
  // texture from the anchor's CURRENT (mid-drag) geometry on every move,
  // rAF-coalesced. Three deliberate choices keep this cheap enough for a
  // 60fps drag where the drag-END regenerate (a full remove+recreate+
  // toDataURL) is not:
  // 1. The raster's existing canvas is redrawn in place (no allocation, no
  //    new Paper item, no undo churn) and its bounds updated.
  // 2. NO toDataURL — the persistable data.src is only refreshed by the
  //    full regenerate() at drag end (which replaces the raster anyway).
  // 3. The engine-side texture is re-uploaded under the SAME image id via
  //    registerImagePixels — engine.rs's images HashMap insert() OVERWRITES
  //    an existing key (verified in the Rust source before building this),
  //    so a long drag re-uploads in place instead of accumulating hundreds
  //    of orphaned textures in the engine's session-lifetime image cache.
  var _liveRestampPending = false;
  function liveRestamp(basePath, layer) {
    if (!basePath.data || !basePath.data.bitmapBrushSpec || !basePath.data.brushCompanions) return;
    var raster = basePath.data.brushCompanions[0];
    if (!raster || raster.removed || !(raster instanceof Raster)) return;
    if (_liveRestampPending) return;
    _liveRestampPending = true;
    requestAnimationFrame(function () {
      _liveRestampPending = false;
      if (raster.removed) return;
      var bake = bakeToCanvas(basePath, basePath.data.bitmapBrushSpec, raster.canvas);
      raster.position = new Point(bake.minX + bake.w / 2, bake.minY + bake.h / 2);
      raster.size = new Size(bake.w, bake.h);
      if (window.SMEngineBridge && raster.data.src) SMEngineBridge.registerImagePixels(raster.data.src, bake.canvas);
      if (window.SMEngineBridge) SMEngineBridge.renderNow();
    });
  }

  // ---- eraser support (v2.1): pixel-erase, raster-app semantics ----
  // eraseAtPoint (tools.js) can't apply here: its boolean-cut pipeline
  // replaces the bitten path with fresh geometry that loses .data entirely
  // (bitmapBrushSpec/brushGroupId gone → orphaned companion). The natural
  // semantics for a baked bitmap texture is what every raster app does:
  // erase PIXELS from the texture (destination-out capsule), leave the
  // anchor's vector geometry intact. Deliberate consequence, not a bug: a
  // later node edit re-stamps the full texture procedurally, resurrecting
  // erased areas — same "the texture is derived, the path is the source of
  // truth" model as everything else in this module.
  // data.src (the persisted dataURL) intentionally NOT refreshed per bite
  // (toDataURL per pointermove would be the exact freeze this file's
  // MAX_TEX clamp comment describes) — bites mark the raster dirty and
  // flushEraseDirty() refreshes once at gesture end.
  function eraseBite(raster, worldPt, radius, fromPt) {
    var cv = raster.canvas;
    if (!cv || !cv.width) return;
    var b = raster.bounds;
    var sx = cv.width / b.width, sy = cv.height / b.height;
    var ctx = cv.getContext('2d');
    ctx.save();
    ctx.globalCompositeOperation = 'destination-out';
    ctx.beginPath();
    var px = (worldPt.x - b.x) * sx, py = (worldPt.y - b.y) * sy, pr = radius * sx;
    if (fromPt) {
      // Capsule from the previous sample — same gap-free continuous-drag
      // reasoning as buildEraserCapsule (tools.js), just in pixel space.
      var fx = (fromPt.x - b.x) * sx, fy = (fromPt.y - b.y) * sy;
      ctx.lineCap = 'round'; ctx.lineWidth = pr * 2;
      ctx.strokeStyle = '#000';
      ctx.moveTo(fx, fy); ctx.lineTo(px, py); ctx.stroke();
    }
    ctx.arc(px, py, pr, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();
    raster.data._bmbEraseDirty = true;
    if (window.SMEngineBridge && raster.data.src) SMEngineBridge.registerImagePixels(raster.data.src, cv);
  }
  function flushEraseDirty(layer) {
    if (!layer) return;
    layer.children.forEach(function (c) {
      if (c instanceof Raster && c.data && c.data._bmbEraseDirty && c.canvas) {
        c.data.src = c.canvas.toDataURL('image/png');
        delete c.data._bmbEraseDirty;
      }
    });
  }

  // Tween in-between re-stamp (tweens.js's generateTweens, mirroring
  // dabRecordsForTween's role for the vector presets) — found live via
  // stress-testing (2026-07, "keyframes avec les brush"): a bitmap-brush
  // stroke on two keyframes generated tween IN-BETWEEN frames with NO
  // texture at all (the companion Raster is correctly excluded from shape
  // matching, same as vector dabs, but nothing re-stamped it for the
  // generated frames — the vector presets have dabRecordsForTween for
  // exactly this, bitmap brush had no equivalent). Builds a throwaway Path
  // from the INTERPOLATED anchor's own segments (tweens.js already
  // computed these — this file never touches matching/interpolation
  // itself) and bakes a texture from it, returning a plain serialized
  // stroke record (matching serR's shape) — tweens.js pushes it into that
  // frame's strokes array directly, same as it does for dabRecordsForTween's
  // vector records.
  function recordForTween(segmentsData, closed, spec, opacityMul, groupId) {
    var p = new Path({ insert: false });
    segmentsData.forEach(function (s) {
      p.add(new Segment(new Point(s.point[0], s.point[1]), new Point(s.handleIn[0], s.handleIn[1]), new Point(s.handleOut[0], s.handleOut[1])));
    });
    if (closed) p.closed = true;
    if (p.segments.length < 2) { p.remove(); return null; }
    var bake = bakeToCanvas(p, spec, null);
    p.remove();
    var dataUrl = bake.canvas.toDataURL('image/png');
    return {
      isRaster: true, src: dataUrl,
      x: bake.minX + bake.w / 2, y: bake.minY + bake.h / 2,
      width: bake.w, height: bake.h,
      opacity: (spec.opacity != null ? spec.opacity : 1) * (opacityMul != null ? opacityMul : 1),
      isBrushTextureCopy: true, isBitmapBrush: true, brushGroupId: groupId,
    };
  }

  // regenerateBrushTexture's (tools.js) bitmap branch — remove this
  // anchor's companions and re-stamp from its CURRENT geometry, reusing
  // the stored spec (same seed: a re-stamp after a node drag must not make
  // the texture "boil", same determinism rule as the vector dabs).
  function regenerate(basePath, layer) {
    if (!basePath.data || !basePath.data.bitmapBrushSpec) return;
    var gid = basePath.data.brushGroupId;
    for (var i = layer.children.length - 1; i >= 0; i--) {
      var c = layer.children[i];
      if (c !== basePath && c.data && c.data.isBrushTextureCopy && c.data.brushGroupId === gid) c.remove();
    }
    // Re-apply reads color from preTextureStroke (strokeColor is nulled by
    // now on a fill anchor) or the stored spec — pass the stored spec
    // through untouched.
    applyBitmapBrushTexture(basePath, basePath.data.bitmapBrushSpec);
  }

  // ---- live drag preview: DOM canvas layered over the Rust canvas,
  // stamped incrementally in SCREEN space (see file header) ----
  var liveCanvas = null, liveCtx = null, liveTip = null, liveLastPt = null, liveAcc = 0, liveSeed = 0;
  function ensureLiveCanvas() {
    if (liveCanvas) return liveCanvas;
    var rust = document.getElementById('rust-canvas');
    var paper = document.getElementById('drawing-canvas');
    var host = (rust || paper) && (rust || paper).parentNode;
    if (!host) return null;
    liveCanvas = document.createElement('canvas');
    liveCanvas.id = 'bitmap-brush-live';
    liveCanvas.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:5;';
    var after = rust || paper;
    after.parentNode.insertBefore(liveCanvas, after.nextSibling);
    liveCtx = liveCanvas.getContext('2d');
    return liveCanvas;
  }
  function beginLivePreview() {
    var c = ensureLiveCanvas(); if (!c) return;
    var area = document.getElementById('canvas-area');
    var rect = area.getBoundingClientRect();
    var dpr = window.devicePixelRatio || 1;
    // Sized/cleared fresh each stroke (canvas resize implicitly clears —
    // exactly what's wanted here, no stale texture from a previous stroke).
    c.width = Math.max(1, Math.round(rect.width * dpr));
    c.height = Math.max(1, Math.round(rect.height * dpr));
    liveCtx.setTransform(dpr, 0, 0, dpr, 0, 0);
    liveCtx.clearRect(0, 0, rect.width, rect.height);
    liveOriginX = rect.left; liveOriginY = rect.top;
    liveLastPt = null; liveAcc = 0;
    liveSeed = Math.floor(Math.random() * 0xffffffff);
    // Tint the tip with the actual brush color ONCE per stroke (color is
    // fixed for the whole gesture) rather than per stamp — same
    // white-mask + destination-in tint the real bake uses, just done once
    // here since it's cheap to do once and expensive-in-spirit to redo per
    // stamp for a preview that just needs to look right, not be exact.
    var mask = buildTipCanvas(state.bitmapTip || 'soft', liveSeed);
    liveTip = document.createElement('canvas');
    liveTip.width = mask.width; liveTip.height = mask.height;
    var tctx = liveTip.getContext('2d');
    tctx.fillStyle = state.strokeColor || '#000000';
    tctx.fillRect(0, 0, mask.width, mask.height);
    tctx.globalCompositeOperation = 'destination-in';
    tctx.drawImage(mask, 0, 0);
  }
  var liveOriginX = 0, liveOriginY = 0;
  // Called on every pointermove with the RAW client (screen) coordinates —
  // draw-bridge.js already has these before any world-space conversion.
  // Only stamps the segment between the last call and this one (never
  // redraws earlier segments), so cost per call is independent of how long
  // the stroke has gotten so far.
  function livePreviewMove(clientX, clientY, pressureWidthMul) {
    if (!liveCanvas || !liveCtx) return;
    var x = clientX - liveOriginX, y = clientY - liveOriginY;
    var zoom = (window.view && view.zoom) || 1;
    var baseSize = (state.bitmapSize || 40) * zoom; // approximate world size at current zoom
    var spacing = Math.max(1, baseSize * ((state.bitmapSpacing != null ? state.bitmapSpacing : 15) / 100));
    var scatterPx = baseSize * ((state.bitmapScatter != null ? state.bitmapScatter : 20) / 100);
    var opacity = (state.bitmapOpacity != null ? state.bitmapOpacity : 100) / 100;
    var rng = seededRng(liveSeed + Math.floor(x + y)); // cheap per-call variance, not a strict determinism guarantee (preview only)
    if (!liveLastPt) {
      liveLastPt = [x, y];
      stampLive(x, y, baseSize * (pressureWidthMul || 1), scatterPx, opacity, rng);
      return;
    }
    var dx = x - liveLastPt[0], dy = y - liveLastPt[1];
    var segLen = Math.sqrt(dx * dx + dy * dy);
    if (segLen < 1e-6) return;
    var acc = liveAcc;
    while (acc < segLen) {
      var t = acc / segLen;
      stampLive(liveLastPt[0] + dx * t, liveLastPt[1] + dy * t, baseSize * (pressureWidthMul || 1), scatterPx, opacity, rng);
      acc += spacing;
    }
    liveAcc = acc - segLen;
    liveLastPt = [x, y];
  }
  function stampLive(x, y, size, scatterPx, opacity, rng) {
    var jx = (rng() - 0.5) * 2 * scatterPx, jy = (rng() - 0.5) * 2 * scatterPx;
    var s = size * (0.75 + rng() * 0.5);
    liveCtx.save();
    liveCtx.globalAlpha = opacity;
    // Plain source-over (default) with a pre-colored tip — overlapping
    // stamps naturally build up coverage where they intersect, close
    // enough to the real bake's look for a live preview.
    liveCtx.drawImage(liveTip, x + jx - s / 2, y + jy - s / 2, s, s);
    liveCtx.restore();
  }
  function endLivePreview() {
    if (!liveCanvas) return;
    liveCtx.clearRect(0, 0, liveCanvas.width, liveCanvas.height);
    liveLastPt = null;
  }

  // ---- panel wiring — plain state fields, same convention as every other
  // scrub/select input in this app (ui.js) ----
  function bindNum(id, key, def) {
    var el = document.getElementById(id); if (!el) return;
    state[key] = def;
    el.addEventListener('change', function () { state[key] = parseFloat(this.value) || def; });
    el.addEventListener('input', function () { state[key] = parseFloat(this.value) || def; });
  }
  function init() {
    var onEl = document.getElementById('p-bitmapbrush-on');
    if (onEl) { state.bitmapBrushOn = false; onEl.addEventListener('change', function () { state.bitmapBrushOn = this.checked; }); }
    // Tip is now picked via bitmap-tip-picker.js's swatch popover (panel
    // reorg pass) — state.bitmapTip's default lives here since this file
    // still owns that state field, the picker only ever writes to it.
    if (state.bitmapTip === undefined) state.bitmapTip = 'soft';
    bindNum('p-bitmap-size', 'bitmapSize', 40);
    bindNum('p-bitmap-spacing', 'bitmapSpacing', 15);
    bindNum('p-bitmap-scatter', 'bitmapScatter', 20);
    bindNum('p-bitmap-opacity', 'bitmapOpacity', 100);
    var pressEl = document.getElementById('p-bitmap-pressure');
    if (pressEl) { state.bitmapPressure = pressEl.checked; pressEl.addEventListener('change', function () { state.bitmapPressure = this.checked; }); }

    // ---- Apply / Remove to selection ("changer taille, type de brush et
    // autre paramètre une fois appliqué et dessiné" + "passer d'un brush
    // vecto à texturé et inversement") — mirrors the vector preset panel's
    // own "Apply to selection" button (timeline.js) exactly, including
    // reuse of the SAME shared stripAnyBrushTexture (app.js) so converting
    // either direction, or just re-editing a bitmap stroke's own
    // tip/size/spacing/scatter in place, all go through one clean path. ----
    var applyBtn = document.getElementById('btn-bitmap-apply');
    if (applyBtn) applyBtn.addEventListener('click', function () {
      var eligible = selectedPaths.filter(function (p) { return p instanceof Path && !(p.data && (p.data.isVectorBrush || p.data.isFillShape)) && (p.strokeColor || p.fillColor || (p.data && (p.data.brushTexturePreset || p.data.bitmapBrushSpec))); });
      if (!eligible.length) { if (window.showToast) showToast('Sélectionne au moins un trait'); return; }
      pushUndo();
      eligible.forEach(function (p) {
        stripAnyBrushTexture(p);
        applyBitmapBrushTexture(p);
      });
      saveActiveLayerFrame(); updateUI();
      if (window.SMEngineBridge) SMEngineBridge.renderNow();
      if (window.showToast) showToast('Bitmap Brush appliqué à la sélection');
    });
    var removeBtn = document.getElementById('btn-bitmap-remove');
    if (removeBtn) removeBtn.addEventListener('click', function () {
      var eligible = selectedPaths.filter(function (p) { return p instanceof Path && p.data && (p.data.bitmapBrushSpec || p.data.brushTexturePreset); });
      if (!eligible.length) { if (window.showToast) showToast('Aucun trait texturé sélectionné'); return; }
      pushUndo();
      eligible.forEach(function (p) { stripAnyBrushTexture(p); });
      saveActiveLayerFrame(); updateUI();
      if (window.SMEngineBridge) SMEngineBridge.renderNow();
      if (window.showToast) showToast('Texture retirée');
    });

    // ---- ABR import ----
    var abrBtn = document.getElementById('btn-bitmap-import-abr');
    var abrFile = document.getElementById('bitmap-abr-file');
    if (abrBtn && abrFile) {
      abrBtn.addEventListener('click', function () { abrFile.click(); });
      abrFile.addEventListener('change', function () {
        var file = this.files && this.files[0];
        this.value = ''; // allow re-importing the same file name later
        if (!file || !window.SMAbrImport) return;
        var reader = new FileReader();
        reader.onload = function () {
          var tipsFound;
          try { tipsFound = window.SMAbrImport.readAbrArrayBuffer(reader.result); }
          catch (e) { if (window.showToast) showToast('Import .abr échoué : ' + e.message); return; }
          var lastId = null;
          tipsFound.forEach(function (t, i) {
            var id = 'abr_' + Date.now().toString(36) + '_' + i;
            customTips[id] = { name: t.name, canvas: t.canvas };
            lastId = id;
          });
          // Picker swatch (bitmap-tip-picker.js) owns the visible label/
          // preview now — select the just-imported tip and repaint it.
          if (lastId) { state.bitmapTip = lastId; if (window.BitmapTipPicker) window.BitmapTipPicker.paintButton(lastId); }
          if (window.showToast) showToast(tipsFound.length + ' tip(s) importé(s) depuis ' + file.name);
        };
        reader.onerror = function () { if (window.showToast) showToast('Lecture du fichier .abr échouée'); };
        reader.readAsArrayBuffer(file);
      });
    }
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();

  window.SMBitmapBrush = {
    applyToPath: applyBitmapBrushTexture,
    regenerate: regenerate,
    liveRestamp: liveRestamp,
    recordForTween: recordForTween,
    eraseBite: eraseBite,
    flushEraseDirty: flushEraseDirty,
    beginLivePreview: beginLivePreview,
    livePreviewMove: livePreviewMove,
    endLivePreview: endLivePreview,
    // ---- for bitmap-tip-picker.js (panel-reorg pass) ----
    tipGroups: function () { return TIP_GROUPS; },
    customTipKeys: function () { return Object.keys(customTips); },
    customTipName: function (key) { return customTips[key] && customTips[key].name; },
    buildTipCanvas: buildTipCanvas,
    registerCustomTip: function (id, name, canvas) { customTips[id] = { name: name, canvas: canvas }; },
  };
})();
