'use strict';
// Deterministic JSON, CSV and Markdown serialization of a built inventory.

function csvOf(inv) {
  const esc = (v) => '"' + String(v === undefined || v === null ? '' : Array.isArray(v) ? v.join(' | ') : typeof v === 'object' ? Object.entries(v).map(([k, d]) => k + '@' + d).join(' ') : v).replace(/"/g, '""') + '"';
  const cols = ['id', 'kind', 'area', 'surface', 'capability', 'handler', 'events', 'exposure', 'sdk', 'mcp', 'consumers', 'fixtures', 'platforms', 'status', 'nextGate', 'source', 'reason'];
  return cols.join(',') + '\n' + inv.rows.map((r) => cols.map((c) => esc(r[c])).join(',')).join('\n') + '\n';
}

function mdOf(inv) {
  const c = inv.counts;
  const tbl = (obj) => Object.entries(obj).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`).join('\n');
  const unmapped = inv.rows.filter((r) => r.status === 'unmapped');
  const placeholders = inv.rows.filter((r) => r.status === 'unavailable-with-reason');
  const cell = (s) => String(s).replace(/\|/g, '/');
  const fixturesByArea = inv.fixturesByArea || {};
  return `# Nemo surface inventory

Generated by \`scripts/nemo/inventory.cjs\` (v${inv.generatorVersion}) from source \`${inv.source.head.slice(0, 12)}\` (${inv.source.describe}).
Inputs digest \`${inv.inputsDigest.slice(0, 12)}\`. Do not edit by hand; run \`npm run inventory\`. \`npm run inventory -- --check\` fails when this file is stale.

Row schema: \`surface -> capability -> handler -> UI/SDK/MCP exposure -> consumers -> fixtures -> platform status -> next gate\`.
Full data: [surfaces.json](surfaces.json) (all fields) and [surfaces.csv](surfaces.csv).

## Counts

| Kind | Rows |
|---|---|
${tbl(c.byKind)}

| Status | Rows |
|---|---|
${tbl(c.byStatus)}

| Area | Rows | Fixtures covering the area |
|---|---|---|
${Object.entries(c.byArea).sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} | ${(fixturesByArea[k] || []).join(', ') || '(none yet)'} |`).join('\n')}

| Consumer reached (≤3 calls from the handler) | Rows |
|---|---|
${tbl(c.byConsumer)}

Consumer detection is static reachability from the bound handler through named
function calls, capped at three hops and 600 visited functions; a depth of \`1\`
means the handler body itself contains the consumer call. It over-approximates
through hub functions (\`updateUI\`, \`renderNow\`) and cannot see dynamic dispatch,
so treat it as "may touch", never as proof of coverage.

## How rows are found

- **dom** — every \`button\`, \`input\`, \`select\`, \`textarea\`, \`a\`, element with a
  \`data-tool/-tab/-pane/-mode/-value/-key/-align/...\` attribute, or an actionable
  class in \`src/index.html\`. A row is \`inventoried\` only when static analysis finds
  an **event registration** on that element (\`addEventListener\` or \`on<event> =\`),
  reached from a \`getElementById('id')\` / \`querySelector('#id')\` lookup through the
  element's own member chain, the variable it is assigned to (same function scope,
  latest assignment wins, shadowed names excluded), a helper that receives the element
  or its id as a parameter, a \`forEach\` callback over \`querySelectorAll\`, a selector
  scoped to the element, an id table (\`getElementById(IDS[key])\`) or id array
  (\`['a','b'].forEach(id => …)\`), a compound selector (\`#bar .cls[data-x]\`), or
  delegation on a bound ancestor (\`e.target\` / \`.closest\`). Comments, strings and
  template literals are never read. A lookup that only reads or writes the element
  (\`.value\`, \`.disabled\`, \`.textContent\`, …) is a *reference*: it is listed with the
  row but does not bind it, so such controls stay explicit \`unmapped\` rows below.
  A control whose container is emptied and rebuilt at runtime is
  \`unavailable-with-reason\` (static placeholder).
- **shortcut** — the \`TOOL_SHORTCUTS\`, \`COMMAND_SHORTCUTS\` and \`READONLY_SHORTCUTS\`
  tables in \`src/js/timeline.js\`.
- **menu** — every object literal \`{label: …, action|run|onClick: …}\` in \`src/js\`
  (context menus, layer "+" menu, tween/curve menus).
- **labs** — every \`SMLabs.register('name', {...})\` under \`src/js/labs\`.
- **sdk** — the scripting API (\`nemo-script.js\`) and plugin API (\`nemo-plugin.js\`): object-literal
  members (namespaced, e.g. \`selection.layers\`), \`Class.prototype\` accessor properties and
  methods (\`Layer.name\`, \`Layer.strokes()\`).

MCP exposure is \`none\` for every row until R14 adds the adapter.

## Module globals (not rows)

${Object.keys(inv.globals).length} \`window.SM*\` objects expose ${Object.values(inv.globals).reduce((s, g) => s + g.members, 0)} function members between files. They are internal bridges, not shipped surfaces; the scripting API rows above are the supported script entry points.

| Global | Defined in | Function members |
|---|---|---|
${Object.entries(inv.globals).sort().map(([k, g]) => `| ${k} | ${g.file}:${g.line} | ${g.members} |`).join('\n')}

## Unmapped surfaces (${unmapped.length})

Rows with no event registration found by static analysis. Each needs either a
binding (then it becomes \`inventoried\`) or an explicit \`unavailable-with-reason\`.
"Referenced at" lists the places that read or write the element without registering
an event: the control's effect, if any, goes through the handler of another surface
(a form field read on submit, a state toggled from a menu). Decorative or purely
CSS-driven controls belong in \`unavailable-with-reason\`.

| Row | Area | Capability | Source | Referenced at |
|---|---|---|---|---|
${unmapped.map((r) => `| \`${r.id}\` | ${r.area} | ${cell(r.capability)} | ${r.source} | ${cell(((r.meta && r.meta.references) || []).join(', ') || '—')} |`).join('\n')}

## Static placeholders (${placeholders.length})

Markup present in \`src/index.html\` that its container empties and rebuilds at runtime
before it can receive input; the live controls are created and bound by the builder
named in the reason. Status \`unavailable-with-reason\`.

| Row | Area | Reason |
|---|---|---|
${placeholders.map((r) => `| \`${r.id}\` | ${r.area} | ${cell(r.reason)} |`).join('\n')}
`;
}

function renderOutputs(inv) {
  const json = JSON.stringify(inv, null, 1) + '\n';
  return { 'surfaces.json': json, 'surfaces.csv': csvOf(inv), 'SURFACES.md': mdOf(inv) };
}

module.exports = { renderOutputs };
