#!/usr/bin/env node
'use strict';
// Regenerates the R03 fixture corpus and its manifest.
//
//   node tests/fixtures/generate.cjs            write tests/fixtures/<id>/… and manifest.json
//   node tests/fixtures/generate.cjs --check    render in memory and compare byte-for-byte
//
// Everything written here is deterministic for a given generator version and
// supported zlib build (see README.md, Generator runtime):
// documents come from tests/fixtures/lib/corpus.cjs, expectations from
// tests/fixtures/lib/reference.cjs, assets from the dependency-free PNG
// encoder. The manifest pins each committed file by SHA-256, so
// tests/fixtures/fixtures.test.cjs can tell a hand-edited fixture from a
// generated one, and `--check` tells a stale corpus from a current one.
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const corpus = require('./lib/corpus.cjs');
const { seedFrom } = require('./lib/rng.cjs');

const GENERATOR_VERSION = 1;
// Pin the compression builds verified to reproduce the version-1 corpus. A
// Node major alone is insufficient: distributors may link a different zlib.
// Keep this independent of the committed manifest so corruption cannot redefine
// the generation contract. Admit another build only after exact-byte validation.
const GENERATOR_ZLIB_BUILDS = new Set([
  '1.3.0.1-motley-209717d',
  '1.3.0.1-motley-71660e1',
  '1.3.0.1-motley-780819f',
  '1.3.0.1-motley-82a5fec',
  '1.3.1-e00f703',
  '1.3.2.1-motley-42c2f19',
]);
const DIR = __dirname;
const REL = (p) => path.relative(path.resolve(DIR, '..', '..'), p).split(path.sep).join('/');

function sha256(buf) { return crypto.createHash('sha256').update(buf).digest('hex'); }

function render() {
  if (!GENERATOR_ZLIB_BUILDS.has(process.versions.zlib)) {
    const error = new Error(`incompatible fixture generator runtime: Node ${process.version}, zlib ${process.versions.zlib}; use the official Node 20.19.4 build (zlib 1.3.0.1-motley-82a5fec) or a verified build listed in tests/fixtures/README.md. Do not regenerate assets to resolve runtime drift.`);
    error.code = 'ERR_FIXTURE_GENERATOR_RUNTIME';
    throw error;
  }
  const files = {}; // relative path (from tests/fixtures) → Buffer
  const entries = [];
  for (const build of corpus.FIXTURES) {
    const fx = build();
    const id = fx.meta.id;
    const projectJson = Buffer.from(JSON.stringify(fx.project, null, 1) + '\n');
    const expectedJson = Buffer.from(JSON.stringify({ schema: 'nemo.fixture-expectations/1', fixture: id, reference: 'tests/fixtures/lib/reference.cjs', checks: fx.expected }, null, 1) + '\n');
    files[`${id}/project.json`] = projectJson;
    files[`${id}/expected.json`] = expectedJson;
    const assets = [];
    for (const [rel, buf] of Object.entries(fx.assets)) { files[`${id}/${rel}`] = buf; assets.push(rel); }
    const hashes = {};
    for (const rel of [`${id}/project.json`, `${id}/expected.json`].concat(assets.map((a) => `${id}/${a}`))) hashes[rel] = sha256(files[rel]);
    const counts = { total: fx.expected.length, node: fx.expected.filter((c) => c.verify === 'node').length, nodeWhenAvailable: fx.expected.filter((c) => c.verify === 'node-when-available').length, gate: fx.expected.filter((c) => c.verify === 'gate').length };
    entries.push(Object.assign({}, fx.meta, {
      seed: seedFrom(id),
      generation: { generator: 'tests/fixtures/generate.cjs', version: GENERATOR_VERSION, builder: `tests/fixtures/lib/corpus.cjs#${build.name}`, formatVersion: fx.project.version },
      files: { project: `${id}/project.json`, expected: `${id}/expected.json`, assets: assets.map((a) => `${id}/${a}`) },
      sha256: hashes,
      checks: counts,
      document: { layers: fx.project.layers.length, totalFrames: fx.project.totalFrames, fps: fx.project.fps, canvas: [fx.project.canvasW, fx.project.canvasH], bytes: projectJson.length },
    }));
  }
  // Synthetic workload documents are not committed (megabytes); they are
  // regenerated by tests/bench from these parameters and verified against
  // the hash recorded here.
  const workloads = [];
  for (const [id, params] of Object.entries(WORKLOAD_DOCS)) {
    const doc = corpus.benchDocument(params);
    const json = JSON.stringify(doc);
    workloads.push({ id, committed: false, generator: 'tests/fixtures/lib/corpus.cjs#benchDocument', params, seed: params.seed, sha256: sha256(json), bytes: json.length, layers: doc.layers.length, totalFrames: doc.totalFrames, itemsPerKeyframe: params.strokesPerKey * params.layers });
  }
  const manifest = {
    schema: 'nemo.fixtures/1',
    generator: { script: 'tests/fixtures/generate.cjs', version: GENERATOR_VERSION },
    formatVersion: corpus.FORMAT_VERSION,
    requiredCoverage: corpus.REQUIRED_COVERAGE,
    checkKinds: CHECK_KINDS,
    fixtures: entries,
    workloads,
  };
  files['manifest.json'] = Buffer.from(JSON.stringify(manifest, null, 1) + '\n');
  return { files, manifest };
}

const WORKLOAD_DOCS = {
  'bench-vectors-40x24': { layers: 40, total: 24, keyEvery: 6, strokesPerKey: 50, seed: seedFrom('bench-vectors-40x24') },
  'bench-vectors-8x24': { layers: 8, total: 24, keyEvery: 6, strokesPerKey: 25, seed: seedFrom('bench-vectors-8x24') },
  'bench-images-20x24': { layers: 20, total: 24, keyEvery: 6, strokesPerKey: 5, withImages: 20, seed: seedFrom('bench-images-20x24') },
};

const CHECK_KINDS = {
  'motion-value': 'SMMotion.valueAtFrame(layer, prop, frame) equals expect within tolerance',
  'expression-error': 'after evaluation, expressions[prop].lastError is set (true) or null (false)',
  'effective-keyframe': 'getEffectiveStrokes(layer, frame) returns the strokes of frames[expectKeyframe] (or nothing)',
  'symbol-frame': 'resolveSymbolFrameIdx gives expectInternalFrame and getEffectiveStrokes returns expectStrokeIds',
  migration: 'the named migration helper produces expect (verify=node) or is recorded for the importJSON contract gate',
  bounds: 'the stroke\'s segment points span expect',
  document: 'the JSON at path equals expect',
  alpha: 'reference hex8 parse',
  mesh: 'topology invariants of imageMeshes[meshId]',
  'mesh-vertex-world': 'vertex index maps to expectRest / expectDeformed in world space over rect',
  'mesh-propagated': 'every frame\'s raster carries meshId',
  'text-units': 'text-selector unitIndexOf returns the stamped char indices',
  'text-group': 'vectorTextGroupMembers(root) over the desP-restored data returns expectMembers, rootStrokeId first',
  'data-url-asset': 'the embedded data URL decodes to the committed asset bytes',
  'image-size': 'the committed asset decodes to expect',
  'frame-pixels': 'the committed frame decodes to the sampled colours',
  'interaction-schema': 'gesture.json is well formed',
  interaction: 'document effect of a replayed gesture (R12 gate)',
  pixel: 'rendered pixel colour at (x, y) on frame within tolerance (R13 gate)',
  encode: 'ffmpeg with the recorded arguments produces the probed stream (when a runnable sidecar is present)',
  'decode-sample': 'a decoded frame of the encoded output matches the samples (when available)',
};

function writeAll(files, root) {
  for (const [rel, buf] of Object.entries(files)) {
    const p = path.join(root, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, buf);
  }
}

function check(files) {
  const stale = [];
  for (const [rel, buf] of Object.entries(files)) {
    const p = path.join(DIR, rel);
    if (!fs.existsSync(p)) { stale.push(`${rel} (missing)`); continue; }
    if (!buf.equals(fs.readFileSync(p))) stale.push(rel);
  }
  return stale;
}

function main() {
  const args = process.argv.slice(2);
  const { files, manifest } = render();
  if (args.includes('--check')) {
    const stale = check(files);
    if (stale.length) { console.error('fixtures stale: ' + stale.join(', ') + ' — run `npm run fixtures`'); process.exit(1); }
    console.log(`fixtures up to date (${manifest.fixtures.length} fixtures, ${Object.keys(files).length} files)`);
    return;
  }
  const out = args.includes('--out') ? path.resolve(args[args.indexOf('--out') + 1]) : DIR;
  writeAll(files, out);
  const bytes = Object.values(files).reduce((a, b) => a + b.length, 0);
  console.log(`fixtures: ${manifest.fixtures.length} fixtures, ${manifest.workloads.length} workload documents, ${Object.keys(files).length} files, ${bytes} bytes -> ${REL(out)}/`);
}

if (require.main === module) {
  try { main(); } catch (error) {
    if (error.code !== 'ERR_FIXTURE_GENERATOR_RUNTIME') throw error;
    console.error(error.message);
    process.exitCode = 2;
  }
}
module.exports = { render, check, WORKLOAD_DOCS, CHECK_KINDS, GENERATOR_VERSION };
